- hosts: all
  user: root
  become: yes
  tasks:
    - name: Add repository
      yum_repository:
          name: epel
          description: EPEL YUM repo
          baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    - name: Install device-mapper-persistent-data
      dnf:
        name: "{{ packages}}"
      vars:
        packages:
        - lvm2
        - device-mapper
        - device-mapper-persistent-data
        - device-mapper-event
        - device-mapper-libs
        - device-mapper-event-libs
    - name: Add localrepo repo
      copy:
        src: /etc/yum.repos.d/httpd.repo
        dest: /etc/yum.repos.d/httpd.repo
        owner: root
        group: root
        mode: '0644'
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
    - name: install containerd rpm from a local file
      dnf:
        name: 'https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm'
        state: present
      register: containerd
    - debug:
         var: containerd

    - name: Install Docker
      dnf:
        name: docker-ce
        state: latest
      become: yes
      register: dockerd
    - debug:
         var: dockerd

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Add user to docker group
      user:
        name: root
        groups: docker
        append: yes
      become: yes
